name: Publish Docker Image

on:
  release:
    types: [published]
  
jobs:
  push_to_registry:
    name: push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: log in to docker hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      
      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: samgd1031/wordle_stats
          
      - name: build and push docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./discord_bot/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
